"""add customer phone number

Revision ID: f3417eaaacd1
Revises: d4393a29fef6
Create Date: 2026-07-21 12:13:59.196020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3417eaaacd1'
down_revision: Union[str, Sequence[str], None] = 'd4393a29fef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'phone_number')
    # ### end Alembic commands ###
